### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [McDiod/TvT_Taplarapu.ruha#1]
- [x] TvT-Template: onPlayerRespawn.sqf,  onPlayerKilled.sqf und cfgFunctions; presetTimeout für gamePaused anpassen
- [x] round time
- [x] sector capture time
- [x] start sector randomization
- [x] fn_endRound
- [x] Fahrzeuge
  - [x] seitenbasiert
  - [x] Texturen
- [x] Spielzone aufräumen
- [x] set last round function
- [x] pause game function
- [x] gamelogic based respawn pos
- [x] move JIP to respawn pos
- [x] Loadouts
- [x] Basen
- [x] skipTime
- [x] weather
- [x] fix replay showing static objects
